In [1]:
import numpy as np

In [2]:
w = np.random.rand(5)
x = np.random.rand(5)
b = np.random.rand(5)

In [3]:
w

array([0.61360161, 0.60698302, 0.07708181, 0.19083013, 0.42637069])

In [4]:
w.shape

(5,)

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-(w*x + b)))

In [16]:
sigmoid(x)

array([0.55112517, 0.54091516, 0.55377497, 0.57450386, 0.62777957])

## Using random seed to ensure reproducibility 

In [ ]:
# When running this cell, each time will give you a different result
x = np.random.rand(5)
x

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [ ]:
# With the help of random seed, when running this cell, each time will give you the same result
np.random.seed(0)
x = np.random.rand(5)
x

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])