## Numpy quick start 
https://numpy.org/doc/stable/user/quickstart.html 

In [3]:
import numpy as np

In [4]:
random_numbers = np.random.rand(10)
print(len(random_numbers))

10


In [5]:
tt = random_numbers.tolist()

In [6]:
tt

[0.551645788964362,
 0.14145060175933932,
 0.36846706895749537,
 0.6220192186720279,
 0.40193486516745236,
 0.6244592779022833,
 0.7527100925806083,
 0.27201678110920213,
 0.859735848574162,
 0.6509955465194006]

In [8]:
ttt = tt * 2

In [9]:
len(ttt)

20

In [11]:
ttt

[0.551645788964362,
 0.14145060175933932,
 0.36846706895749537,
 0.6220192186720279,
 0.40193486516745236,
 0.6244592779022833,
 0.7527100925806083,
 0.27201678110920213,
 0.859735848574162,
 0.6509955465194006,
 0.551645788964362,
 0.14145060175933932,
 0.36846706895749537,
 0.6220192186720279,
 0.40193486516745236,
 0.6244592779022833,
 0.7527100925806083,
 0.27201678110920213,
 0.859735848574162,
 0.6509955465194006]

## 1. DataTypes

In [31]:
a1 = np.array([1, 2, 3])

a2 = np.array([[4, 5, 6], [7, 8, 9]])

a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [29]:
a1.dtype

dtype('float64')

In [30]:
a2.dtype

dtype('int64')

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
a2 * 2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [22]:
a1.shape, a1.ndim, a1.size

((3,), 1, 3)

In [23]:
a2.shape, a2.ndim, a2.size

((2, 3), 2, 6)

In [27]:
a3.shape, a3.ndim, a3.size

((2, 3, 3), 3, 18)

In [17]:
t = [[4, 5, 6], [7, 8, 9]]

In [18]:
t*2

[[4, 5, 6], [7, 8, 9], [4, 5, 6], [7, 8, 9]]

In [32]:
a4 = np.array([[3], [3], [3]])

In [33]:
a1 * a4

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

## 2. Creating arrays

In [34]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
a6 = np.random.randint(0, 10, size=(2, 3), dtype=np.uint8)

In [47]:
a6.dtype

dtype('uint8')

In [48]:
a6

array([[9, 8, 8],
       [8, 7, 0]], dtype=uint8)